//
//  LessonViewModel.swift
//  ProjectDelta
//

import Foundation
import FirebaseFirestore
import Observation
import SwiftUI

@MainActor
@Observable
class LessonViewModel {
    var currentLesson: Lesson?
    var currentLessonName: String = ""
    var currentLessonId: String = ""
    var lessonPages: [Page] = []
    var lessons: [Lesson] = []
    var currentSubjectLessons: [Lesson] = []
    var subjectName: String = ""
    var currentPageIndex: Int = 0
    var currentPageDocumentId: String?
    var isLoading: Bool = true
    var isCurrentPageBookmarked: Bool = false
    
    private let db = Firestore.firestore()
    
    // MARK: - Core Initialization
    
    func initializeLesson(subjectName: String, authVM: AuthViewModel) async {
        self.isLoading = true
        defer { self.isLoading = false }
        
        // Silently fetch curriculum in the background so "Next Lesson" navigation works seamlessly
        self.fetchAllLessons(for: subjectName)
        
        print("Starting to fetch the first incomplete lesson for \(subjectName).")
        let (lessonName, lessonId) = await fetchFirstIncompleteLesson(for: subjectName)
        
        if !lessonName.isEmpty {
            self.currentLessonName = lessonName
            self.currentLessonId = lessonId
            print("First lesson fetched: \(lessonName) with ID \(lessonId)")
            
            print("Starting to fetch lesson content for \(subjectName), lesson \(lessonName).")
            await fetchLessonContent(for: subjectName, lessonName: lessonName)
            print("Content fetching completed for lesson \(lessonName).")
            
            if let initialPageNumber = self.lessonPages.first?.pageNumber {
                await self.navigateToPage(lessonName: lessonName, pageNumber: initialPageNumber, authVM: authVM)
            }
        } else {
            print("No lesson found or fetch failed for subject \(subjectName).")
            self.lessonPages = []
        }
    }
    
    // MARK: - Ghost Subject Resolver
    
    /// Deep-scans the database to find the actual subject document containing populated pages,
    /// completely bypassing any empty ghost documents generated by the Admin panel.
    private func resolveSubjectId(for subjectName: String) async -> String? {
        var candidates = [String]()
        
        // 1. Gather all possible matches (Document ID match + Field name match)
        if let doc = try? await db.collection("Subjects").document(subjectName).getDocument(), doc.exists {
            candidates.append(doc.documentID)
        }
        if let querySnap = try? await db.collection("Subjects").whereField("name", isEqualTo: subjectName).getDocuments() {
            candidates.append(contentsOf: querySnap.documents.map { $0.documentID })
        }
        
        // Remove duplicates
        var uniqueCandidates = [String]()
        for c in candidates where !uniqueCandidates.contains(c) {
            uniqueCandidates.append(c)
        }
        
        // 2. Deep-Scan: Return the first subject that actually has Lessons containing Pages
        for id in uniqueCandidates {
            if let lessonsSnap = try? await db.collection("Subjects").document(id).collection("Lessons").limit(to: 5).getDocuments() {
                for lessonDoc in lessonsSnap.documents {
                    let pages = try? await db.collection("Subjects").document(id).collection("Lessons").document(lessonDoc.documentID).collection("Pages").limit(to: 1).getDocuments()
                    if pages?.isEmpty == false { return id } // Found the real curriculum!
                    
                    let lowerPages = try? await db.collection("Subjects").document(id).collection("Lessons").document(lessonDoc.documentID).collection("pages").limit(to: 1).getDocuments()
                    if lowerPages?.isEmpty == false { return id } // Support both capitalizations
                }
            }
        }
        
        // 3. Fallback: Return a subject that at least has lessons, even if empty
        for id in uniqueCandidates {
            let lessonsSnap = try? await db.collection("Subjects").document(id).collection("Lessons").limit(to: 1).getDocuments()
            if lessonsSnap?.isEmpty == false { return id }
        }
        
        return uniqueCandidates.first
    }
    
    // MARK: - Fetch Logic
    
    func fetchLessonContent(for subjectName: String, lessonName: String) async {
        do {
            guard let subjectId = await resolveSubjectId(for: subjectName) else {
                print("Error: Subject \(subjectName) not found.")
                return
            }
            
            let lessonQuerySnapshot = try await db.collection("Subjects").document(subjectId)
                .collection("Lessons").whereField("name", isEqualTo: lessonName).getDocuments()
            guard let lessonDocument = lessonQuerySnapshot.documents.first,
                  var lesson = try? lessonDocument.data(as: Lesson.self) else {
                print("Lesson \(lessonName) not found within \(subjectName).")
                return
            }
            
            lesson.id = lessonDocument.documentID
            
            var fetchedPages: [Page] = []
            
            // NEW ARCHITECTURE: Read from embedded array
            if let embeddedPages = lesson.pages, !embeddedPages.isEmpty {
                // Generate cryptographically unique IDs to prevent SwiftUI layout crashes from DB corruption
                fetchedPages = embeddedPages.enumerated().map { index, page in
                    var p = page
                    if p.id == nil { p.id = "page_\(index)_\(UUID().uuidString.prefix(6))" }
                    return p
                }.sorted { $0.pageNumber < $1.pageNumber }
            } else {
                // LEGACY ARCHITECTURE: Fallback to subcollection
                var pagesQuerySnapshot = try await db.collection("Subjects").document(subjectId)
                    .collection("Lessons").document(lessonDocument.documentID)
                    .collection("Pages").order(by: "pageNumber").getDocuments()
                
                if pagesQuerySnapshot.isEmpty {
                    pagesQuerySnapshot = try await db.collection("Subjects").document(subjectId)
                        .collection("Lessons").document(lessonDocument.documentID)
                        .collection("pages").order(by: "pageNumber").getDocuments()
                }
                
                fetchedPages = pagesQuerySnapshot.documents.compactMap { document -> Page? in
                    var p = try? document.data(as: Page.self)
                    if p?.id == nil { p?.id = document.documentID }
                    return p
                }
            }
            
            // Forcefully map the state to eliminate logic desyncs during async fetching
            self.lessonPages = fetchedPages
            lesson.pages = fetchedPages
            self.currentLesson = lesson
            self.currentLessonId = lesson.id ?? ""
            self.currentLessonName = lesson.name
            
            if !fetchedPages.isEmpty {
                print("Fetched \(fetchedPages.count) pages for lesson \(lessonName) within \(subjectName).")
            } else {
                print("No pages found for lesson \(lessonName) within \(subjectName).")
            }
            
        } catch {
            print("Firestore query error: \(error.localizedDescription)")
        }
    }
    
    func fetchAllLessons(for subjectName: String) {
        Task {
            do {
                guard let subjectId = await resolveSubjectId(for: subjectName) else {
                    print("Subject \(subjectName) not found")
                    return
                }
                
                let lessonSnapshot = try await db.collection("Subjects").document(subjectId).collection("Lessons").getDocuments()
                guard !lessonSnapshot.isEmpty else {
                    print("No lessons found for subject \(subjectName)")
                    self.currentSubjectLessons = []
                    return
                }
                
                var lessonsWithPages = [Lesson]()
                
                for document in lessonSnapshot.documents {
                    guard var lesson = try? document.data(as: Lesson.self) else { continue }
                    lesson.id = document.documentID
                    
                    // NEW ARCHITECTURE: Read from embedded array
                    if let embeddedPages = lesson.pages, !embeddedPages.isEmpty {
                        lesson.pages = embeddedPages.enumerated().map { index, page in
                            var p = page
                            if p.id == nil { p.id = "page_\(index)_\(UUID().uuidString.prefix(6))" }
                            return p
                        }
                    } else {
                        // LEGACY ARCHITECTURE: Fallback to subcollection
                        var pageSnapshot = try? await db.collection("Subjects").document(subjectId)
                            .collection("Lessons").document(lesson.id!)
                            .collection("Pages").order(by: "pageNumber").getDocuments()
                        
                        if pageSnapshot?.isEmpty == true {
                            pageSnapshot = try? await db.collection("Subjects").document(subjectId)
                                .collection("Lessons").document(lesson.id!)
                                .collection("pages").order(by: "pageNumber").getDocuments()
                        }
                        
                        let legacyPages = pageSnapshot?.documents.compactMap { doc -> Page? in
                            var p = try? doc.data(as: Page.self)
                            if p?.id == nil { p?.id = doc.documentID }
                            return p
                        } ?? []
                        
                        lesson.pages = legacyPages
                    }
                    
                    lessonsWithPages.append(lesson)
                }
                
                self.currentSubjectLessons = lessonsWithPages.sorted { $0.lessonNumber < $1.lessonNumber }
                print("Fetched all lessons and pages for subject \(subjectName)")
                
            } catch {
                print("Error getting lessons for subject \(subjectName): \(error)")
            }
        }
    }
    
    func fetchFirstIncompleteLesson(for subjectName: String) async -> (name: String, id: String) {
        do {
            guard let subjectId = await resolveSubjectId(for: subjectName) else {
                print("Subject \(subjectName) not found.")
                return ("", "")
            }
            
            let lessonsRef = db.collection("Subjects").document(subjectId).collection("Lessons")
            let lessonsSnapshot = try await lessonsRef.whereField("completed", isEqualTo: false).getDocuments()
            
            let documentToUse: QueryDocumentSnapshot
            
            let sortedIncompleteLessons = lessonsSnapshot.documents.sorted {
                let num1 = $0.data()["lessonNumber"] as? Int ?? Int.max
                let num2 = $1.data()["lessonNumber"] as? Int ?? Int.max
                return num1 < num2
            }
            
            if let firstIncomplete = sortedIncompleteLessons.first {
                documentToUse = firstIncomplete
            } else {
                let fallbackSnapshot = try await lessonsRef.getDocuments()
                let sortedAllLessons = fallbackSnapshot.documents.sorted {
                    let num1 = $0.data()["lessonNumber"] as? Int ?? Int.max
                    let num2 = $1.data()["lessonNumber"] as? Int ?? Int.max
                    return num1 < num2
                }
                guard let fallbackDocument = sortedAllLessons.first else {
                    print("No lessons exist in the database for \(subjectName).")
                    return ("", "")
                }
                documentToUse = fallbackDocument
            }
            
            let id = documentToUse.documentID
            let name = documentToUse.data()["name"] as? String ?? "Unknown Name"
            
            self.currentLesson = Lesson(id: id, name: name, description: "", completed: false, lessonNumber: 0, pages: [])
            self.currentLessonId = id
            self.currentLessonName = name
            
            return (name, id)
        } catch {
            print("Error fetching lessons for \(subjectName): \(error)")
            return ("", "")
        }
    }
    
    // MARK: - Navigation
    
    @MainActor
    func navigateToPage(lessonName: String, pageNumber: Int, authVM: AuthViewModel) async {
        if let currentLesson = self.currentLesson, currentLesson.name == lessonName {
            if let pageIndex = currentLesson.pages?.firstIndex(where: { $0.pageNumber == pageNumber }) {
                self.currentPageIndex = pageIndex
                self.currentPageDocumentId = currentLesson.pages?[pageIndex].id
                self.updateBookmarkStatus(authVM: authVM)
            }
        } else {
            // Predictively update the name to trigger loading states
            self.currentLessonName = lessonName
            
            await fetchLessonContent(for: self.subjectName, lessonName: lessonName)
            
            if let pageIndex = self.lessonPages.firstIndex(where: { $0.pageNumber == pageNumber }) {
                self.currentPageIndex = pageIndex
                self.currentPageDocumentId = self.lessonPages[pageIndex].id
                self.updateBookmarkStatus(authVM: authVM)
            } else {
                // Safely fallback to index 0 to guarantee UI doesn't blank out
                self.currentPageIndex = 0
                self.currentPageDocumentId = self.lessonPages.first?.id
                self.updateBookmarkStatus(authVM: authVM)
            }
        }
    }
    
    // MARK: - Lesson Progression
    
    @MainActor
    func advanceToNextLesson(authVM: AuthViewModel) async {
        guard let currentIndex = currentSubjectLessons.firstIndex(where: { $0.id == currentLessonId }),
              currentIndex + 1 < currentSubjectLessons.count else { return }
        
        let nextLesson = currentSubjectLessons[currentIndex + 1]
        await navigateToPage(lessonName: nextLesson.name, pageNumber: 1, authVM: authVM)
    }
    
    // MARK: - Bookmarks
    
    func updateBookmarkStatus(authVM: AuthViewModel) {
        if let lessonId = currentLesson?.id, let pageId = currentPageDocumentId {
            self.isCurrentPageBookmarked = authVM.isPageBookmarked(subjectId: self.subjectName, lessonId: lessonId, pageId: pageId)
        }
    }
    
    func toggleBookmark(authVM: AuthViewModel) {
        if let lessonId = currentLesson?.id, let pageId = currentPageDocumentId {
            if authVM.isPageBookmarked(subjectId: subjectName, lessonId: lessonId, pageId: pageId) {
                authVM.clearPreviousBookmark(subjectId: subjectName, lessonId: lessonId)
            } else {
                authVM.toggleBookmark(subjectId: subjectName, lessonId: lessonId, pageId: pageId)
            }
            updateBookmarkStatus(authVM: authVM)
        }
    }
}
