//
//  ElectromagneticWaveAnalyzerView.swift
//  ProjectDelta
//

import SwiftUI

struct ElectromagneticWaveAnalyzerView: View {
    // MARK: - Properties
    @State private var frequencyLog: Double = 14.55 // Default to Visible Light
    
    // Physics Constants
    private let speedOfLight: Double = 299792458.0
    private let plancksConstant: Double = 6.62607015e-34
    private let joulesToEV: Double = 6.242e18
    
    // Computed Wave Properties
    private var frequency: Double { pow(10, frequencyLog) }
    private var wavelength: Double { speedOfLight / frequency }
    private var photonEnergyJoules: Double { plancksConstant * frequency }
    private var photonEnergyEV: Double { photonEnergyJoules * joulesToEV }
    private var isIonizing: Bool { frequencyLog >= 15.0 }
    
    // MARK: - Data Models
    private struct EMRegion {
        let name: String
        let baseColor: Color
        let gradientColors: [Color]
        let scaleName: String
        let scaleIcon: String
        let applications: [String]
        let description: String
        let icon: String
    }
    
    private struct SpectrumMarker: Identifiable {
        let id = UUID()
        let logValue: Double
        let icon: String
        let baseColor: Color
        let gradientColors: [Color]
    }
    
    private let spectrumMarkers: [SpectrumMarker] = [
        SpectrumMarker(logValue: 3.0, icon: "waveform.path.ecg", baseColor: .teal, gradientColors: [.blue, .teal]),
        SpectrumMarker(logValue: 7.0, icon: "antenna.radiowaves.left.and.right", baseColor: .blue, gradientColors: [.blue, .indigo]),
        SpectrumMarker(logValue: 10.25, icon: "wifi", baseColor: .orange, gradientColors: [.orange, .red]),
        SpectrumMarker(logValue: 12.15, icon: "dot.radiowaves.left.and.right", baseColor: .yellow, gradientColors: [.yellow, .orange]),
        SpectrumMarker(logValue: 13.55, icon: "thermometer.sun.fill", baseColor: .red, gradientColors: [.red, .pink]),
        SpectrumMarker(logValue: 14.55, icon: "eye.fill", baseColor: .green, gradientColors: [.red, .purple]),
        SpectrumMarker(logValue: 15.65, icon: "sun.max.fill", baseColor: .purple, gradientColors: [.purple, .indigo]),
        SpectrumMarker(logValue: 18.0, icon: "xmark.shield.fill", baseColor: .cyan, gradientColors: [.cyan, .blue]),
        SpectrumMarker(logValue: 22.0, icon: "circle.hexagongrid.fill", baseColor: .primary, gradientColors: [.primary, .secondary])
    ]
    
    private var currentRegion: EMRegion {
        switch frequencyLog {
        case ..<5:
            return EMRegion(
                name: "Extremely Low Frequency",
                baseColor: .teal,
                gradientColors: [.blue, .teal],
                scaleName: "Planetary Scale (~10⁷ m)",
                scaleIcon: "globe.americas.fill",
                applications: ["Submarine Communications", "Global Power Grids", "Geophysical Studies", "Lightning Tracking"],
                description: "ELF waves possess immense wavelengths larger than the Earth itself. They can penetrate deep into oceans and solid rock, making them ideal for specialized global communication.",
                icon: "waveform.path.ecg"
            )
        case 5..<9:
            return EMRegion(
                name: "Radio Waves",
                baseColor: .blue,
                gradientColors: [.blue, .indigo],
                scaleName: "Buildings & Mountains (~10² m)",
                scaleIcon: "building.2.fill",
                applications: ["AM/FM Radio Communications", "Television Broadcasts", "Air Traffic Radar Systems", "Magnetic Resonance Imaging"],
                description: "Radio waves possess extremely long wavelengths and low energy. Generated by accelerating charges in conductors, they pass easily through the atmosphere.",
                icon: "antenna.radiowaves.left.and.right"
            )
        case 9..<11.5:
            return EMRegion(
                name: "Microwaves",
                baseColor: .orange,
                gradientColors: [.orange, .red],
                scaleName: "Insects & Humans (~10⁻² m)",
                scaleIcon: "ant.fill",
                applications: ["Microwave Oven Heating", "Wi-Fi & Cellular Data (5G)", "Satellite Transmissions", "Weather Radar"],
                description: "Microwaves cause electric dipole rotation in water molecules, producing kinetic heat. They are widely utilized in high-bandwidth wireless communications.",
                icon: "wifi"
            )
        case 11.5..<12.8:
            return EMRegion(
                name: "Terahertz Waves",
                baseColor: .yellow,
                gradientColors: [.yellow, .orange],
                scaleName: "Human Hair (~10⁻⁴ m)",
                scaleIcon: "lines.measurement.horizontal",
                applications: ["Submillimeter Astronomy", "Security Scanning", "Medical Imaging", "Material Characterization"],
                description: "Sitting between microwaves and infrared, Terahertz radiation (T-Rays) can penetrate many non-conducting materials without ionizing them, offering unique imaging capabilities.",
                icon: "dot.radiowaves.left.and.right"
            )
        case 12.8..<14.3:
            return EMRegion(
                name: "Infrared",
                baseColor: .red,
                gradientColors: [.red, .pink],
                scaleName: "Needle Point & Cells (~10⁻⁵ m)",
                scaleIcon: "circle.inset.filled",
                applications: ["Thermal Imaging Cameras", "Night Vision Systems", "Optical Fiber Communications", "Industrial Heat Sensing"],
                description: "Infrared radiation is emitted by all matter with a temperature above absolute zero (0 K). It corresponds directly to atomic and molecular vibrational modes.",
                icon: "thermometer.sun"
            )
        case 14.3..<14.8:
            return EMRegion(
                name: "Visible Light",
                baseColor: visibleLightColor(for: frequencyLog),
                gradientColors: [.red, .orange, .yellow, .green, .blue, .purple],
                scaleName: "Microorganisms (~10⁻⁶ m)",
                scaleIcon: "sparkles",
                applications: ["Human Photoreception", "Photosynthesis in Plants", "Optical Lasers", "Precision Photography"],
                description: "Visible light encompasses the extremely narrow band detected by the human retina (380 nm - 750 nm). It is produced by electronic transitions in excited atoms.",
                icon: "eye"
            )
        case 14.8..<16.5:
            return EMRegion(
                name: "Ultraviolet",
                baseColor: .purple,
                gradientColors: [.purple, .indigo],
                scaleName: "Molecules & DNA (~10⁻⁸ m)",
                scaleIcon: "cross.vial.fill",
                applications: ["Sterilization & Disinfection", "Fluorescent Material Verification", "Vitamin D Synthesis", "UV Photolithography"],
                description: "Ultraviolet light carries sufficient energy to break chemical bonds. High-frequency UV radiation marks the beginning of dangerous ionizing radiation.",
                icon: "sun.max"
            )
        case 16.5..<19.5:
            return EMRegion(
                name: "X-Rays",
                baseColor: .cyan,
                gradientColors: [.cyan, .blue],
                scaleName: "Atoms (~10⁻¹⁰ m)",
                scaleIcon: "atom",
                applications: ["Diagnostic Medical Imaging", "Airport Baggage Scanning", "X-Ray Crystallography", "Non-Destructive Testing"],
                description: "X-rays are generated by inner-shell electron transitions or deceleration of high-energy electrons (Bremsstrahlung). They readily penetrate soft biological tissue.",
                icon: "xmark.shield"
            )
        default:
            return EMRegion(
                name: "Gamma Rays",
                baseColor: .primary,
                gradientColors: [.primary, .secondary],
                scaleName: "Atomic Nuclei (~10⁻¹⁴ m)",
                scaleIcon: "circle.circle.fill",
                applications: ["Radiation Therapy for Cancer", "Gamma-Ray Astronomy", "Nuclear Submarine Physics", "Medical Instrument Sterilization"],
                description: "Gamma rays are the highest-energy photon emissions, produced by nuclear reactions and radioactive decay. They present significant biological hazards.",
                icon: "exclamationmark.triangle.fill"
            )
        }
    }
    
    private func visibleLightColor(for logValue: Double) -> Color {
        guard logValue >= 14.3 && logValue <= 14.8 else { return .primary }
        let percent = (logValue - 14.3) / 0.5
        let hueValue = percent * 0.75
        return Color(hue: hueValue, saturation: 1.0, brightness: 1.0)
    }
    
    private let spectrumGradient = LinearGradient(
        stops: [
            .init(color: .teal, location: 0.0),
            .init(color: .blue, location: 0.26),
            .init(color: .orange, location: 0.39),
            .init(color: .yellow, location: 0.48),
            .init(color: .red, location: 0.54),
            .init(color: .red, location: 0.575),
            .init(color: .orange, location: 0.58),
            .init(color: .yellow, location: 0.585),
            .init(color: .green, location: 0.59),
            .init(color: .blue, location: 0.595),
            .init(color: .purple, location: 0.60),
            .init(color: .purple, location: 0.63),
            .init(color: .cyan, location: 0.74),
            .init(color: .primary, location: 1.0)
        ],
        startPoint: .leading,
        endPoint: .trailing
    )
    
    // MARK: - Body
    var body: some View {
        GeometryReader { geo in
            let isWide = geo.size.width > 850
            let contentPadding: CGFloat = isWide ? 32 : 20
            // Increased spacing to spread the layout vertically on macOS
            let itemSpacing: CGFloat = isWide ? 24 : 16
            
            ScrollView(.vertical, showsIndicators: false) {
                VStack(alignment: .center, spacing: itemSpacing) {
                    
                    // Indented downwards significantly more for the macOS version
                    headerView(isWide: isWide)
                        .padding(.top, isWide ? 72 : 12)
                        .padding(.bottom, isWide ? 12 : 4)
                    
                    if isWide {
                        // macOS Layout (Expanded)
                        Grid(horizontalSpacing: itemSpacing, verticalSpacing: itemSpacing) {
                            GridRow {
                                metricsBox(stretch: true, isWide: isWide)
                                scaleGraphicBox(stretch: true, isWide: isWide)
                            }
                        }
                        
                        visualizerBox(isWide: isWide)
                        
                        sliderBox(isWide: isWide)
                        
                        Grid(horizontalSpacing: itemSpacing, verticalSpacing: itemSpacing) {
                            GridRow {
                                overviewBox(stretch: true, isWide: isWide)
                                applicationsBox(stretch: true, isWide: isWide)
                            }
                        }
                    } else {
                        // iOS Layout (Reordered)
                        VStack(spacing: itemSpacing) {
                            metricsBox(stretch: false, isWide: isWide)
                            visualizerBox(isWide: isWide)
                            scaleGraphicBox(stretch: false, isWide: isWide)
                            sliderBox(isWide: isWide)
                            overviewBox(stretch: false, isWide: isWide)
                            applicationsBox(stretch: false, isWide: isWide)
                        }
                    }
                }
                .padding(.horizontal, contentPadding)
                .padding(.vertical, 4)
                .padding(.bottom, isWide ? 32 : 120) // Bottom boxes tucked closely
                .frame(maxWidth: 1200)
                .frame(minHeight: geo.size.height, alignment: .top) // Forces stretch to utilize full height
                .frame(maxWidth: .infinity)
            }
        }
        .navigationTitle("EM Wave Analyzer")
#if os(iOS)
        .navigationBarTitleDisplayMode(.inline)
#endif
        .sensoryFeedback(.selection, trigger: frequencyLog)
    }
    
    // MARK: - View Components
    
    private func headerView(isWide: Bool) -> some View {
        VStack(spacing: isWide ? 8 : 6) {
            Image(systemName: currentRegion.icon)
                .font(.system(size: isWide ? 44 : 36, weight: .regular))
                .foregroundStyle(LinearGradient(colors: currentRegion.gradientColors, startPoint: .topLeading, endPoint: .bottomTrailing))
                .shadow(color: currentRegion.baseColor.opacity(0.6), radius: 6, x: 0, y: 0)
                .symbolEffect(.bounce, value: currentRegion.name)
            
            Text(currentRegion.name)
                .font(.system(size: isWide ? 40 : 32, weight: .medium, design: .rounded))
                .tracking(1.5)
                .foregroundStyle(LinearGradient(colors: currentRegion.gradientColors, startPoint: .leading, endPoint: .trailing))
                .contentTransition(.numericText())
                .frame(height: isWide ? 44 : 36)
            
            HStack(spacing: 6) {
                if currentRegion.name == "Visible Light" {
                    Image(systemName: "rainbow")
                    Text("Optical Spectrum")
                        .font((isWide ? Font.body : Font.caption).weight(.bold))
                } else {
                    Image(systemName: isIonizing ? "exclamationmark.triangle.fill" : "checkmark.shield.fill")
                    Text(isIonizing ? "Ionizing Radiation" : "Non-Ionizing Radiation")
                        .font((isWide ? Font.body : Font.caption).weight(.bold))
                }
            }
            .padding(.horizontal, 12)
            .padding(.vertical, isWide ? 6 : 4)
            .background(
                Group {
                    if currentRegion.name == "Visible Light" {
                        LinearGradient(colors: [.red, .orange, .yellow, .green, .blue, .purple], startPoint: .leading, endPoint: .trailing).opacity(0.15)
                    } else if isIonizing {
                        Color.red.opacity(0.15)
                    } else {
                        Color.green.opacity(0.15)
                    }
                }
            )
            .foregroundStyle(currentRegion.name == "Visible Light" ? Color.primary : (isIonizing ? Color.red : Color.green))
            .clipShape(Capsule())
            .overlay(
                Capsule().stroke(currentRegion.name == "Visible Light" ? Color.primary.opacity(0.1) : (isIonizing ? Color.red.opacity(0.2) : Color.green.opacity(0.2)), lineWidth: 1)
            )
        }
    }
    
    private func metricsBox(stretch: Bool, isWide: Bool) -> some View {
        PremiumCard(baseColor: currentRegion.baseColor, gradientColors: currentRegion.gradientColors, stretchVertically: stretch, isWide: isWide) {
            Grid(alignment: .leading, horizontalSpacing: 16, verticalSpacing: isWide ? 20 : 14) {
                GridRow {
                    Text("Frequency (f):")
                        .font(isWide ? .title3 : .headline)
                        .foregroundStyle(.secondary)
                    Text("\(frequency.formatted(.number.notation(.scientific))) Hz")
                        .font((isWide ? Font.title3 : Font.headline).weight(.bold))
                        .monospacedDigit()
                        .lineLimit(1)
                        .minimumScaleFactor(0.5)
                }
                GridRow {
                    Text("Wavelength (λ):")
                        .font(isWide ? .title3 : .headline)
                        .foregroundStyle(.secondary)
                    Text("\(wavelength.formatted(.number.notation(.scientific))) m")
                        .font((isWide ? Font.title3 : Font.headline).weight(.bold))
                        .monospacedDigit()
                        .lineLimit(1)
                        .minimumScaleFactor(0.5)
                }
                GridRow {
                    Text("Photon Energy (E):")
                        .font(isWide ? .title3 : .headline)
                        .foregroundStyle(.secondary)
                    Text("\(photonEnergyJoules.formatted(.number.notation(.scientific))) J")
                        .font((isWide ? Font.title3 : Font.headline).weight(.bold))
                        .monospacedDigit()
                        .lineLimit(1)
                        .minimumScaleFactor(0.5)
                }
            }
        }
    }
    
    private func scaleGraphicBox(stretch: Bool, isWide: Bool) -> some View {
        PremiumCard(baseColor: currentRegion.baseColor, gradientColors: currentRegion.gradientColors, stretchVertically: stretch, isWide: isWide) {
            VStack(alignment: .leading, spacing: isWide ? 18 : 14) {
                Text("Wavelength Scale Equivalent")
                    .font((isWide ? Font.title3 : Font.headline).weight(.semibold))
                    .foregroundStyle(.secondary)
                
                HStack(spacing: 16) {
                    Image(systemName: currentRegion.scaleIcon)
                        .font(.system(size: isWide ? 40 : 32))
                        .foregroundStyle(LinearGradient(colors: currentRegion.gradientColors, startPoint: .topLeading, endPoint: .bottomTrailing))
                        .frame(width: isWide ? 64 : 56, height: isWide ? 64 : 56)
                        .background(currentRegion.baseColor.opacity(0.15))
                        .clipShape(Circle())
                    
                    VStack(alignment: .leading, spacing: 6) {
                        Text("Comparable Physical Scale:")
                            .font(isWide ? .body : .callout)
                            .foregroundStyle(.secondary)
                        Text(currentRegion.scaleName)
                            .font((isWide ? Font.title2 : Font.title3).weight(.semibold))
                            .foregroundStyle(.primary)
                            .lineLimit(2)
                            .minimumScaleFactor(0.8)
                    }
                }
            }
        }
    }
    
    private func visualizerBox(isWide: Bool) -> some View {
        PremiumCard(title: "Transverse Field Oscillations", icon: "waveform.path.ecg", baseColor: currentRegion.baseColor, gradientColors: currentRegion.gradientColors, isWide: isWide) {
            VStack(spacing: 8) {
                HStack(spacing: 16) {
                    Spacer()
                    Label("Electric (E)", systemImage: "line.diagonal")
                        .font((isWide ? Font.body : Font.subheadline).weight(.semibold))
                        .foregroundStyle(LinearGradient(colors: currentRegion.gradientColors, startPoint: .leading, endPoint: .trailing))
                    Label("Magnetic (B)", systemImage: "line.diagonal")
                        .font((isWide ? Font.body : Font.subheadline).weight(.semibold))
                        .foregroundStyle(LinearGradient(colors: [.blue, .cyan], startPoint: .leading, endPoint: .trailing))
                }
                .padding(.bottom, -8)
                .zIndex(1)
                
                // Maximized heights for macOS to consume available horizontal card width gracefully
                DualFieldWaveVisualizer(frequencyLog: frequencyLog, gradientColors: currentRegion.gradientColors)
                    .frame(minHeight: isWide ? 90 : 60, idealHeight: isWide ? 120 : 80)
            }
        }
    }
    
    private func sliderBox(isWide: Bool) -> some View {
        PremiumCard(title: "Spectrum Frequency Scale (10ˣ Hz)", icon: "slider.horizontal.3", baseColor: currentRegion.baseColor, gradientColors: currentRegion.gradientColors, isWide: isWide) {
            VStack(spacing: isWide ? 16 : 12) {
                // Track Markers
                GeometryReader { geo in
                    let range = 23.0 // Log scale from 1 to 24
                    ForEach(spectrumMarkers) { marker in
                        let percent = (marker.logValue - 1.0) / range
                        let isActive = abs(frequencyLog - marker.logValue) <= 0.8
                        
                        let isVisibleLightMarker = marker.logValue == 14.55
                        let activeGradient = (isVisibleLightMarker && currentRegion.name == "Visible Light") ? currentRegion.gradientColors : marker.gradientColors
                        
                        Image(systemName: marker.icon)
                            .font(.system(size: isActive ? (isWide ? 28 : 22) : (isWide ? 16 : 14), weight: .bold))
                            .foregroundStyle(isActive ? LinearGradient(colors: activeGradient, startPoint: .topLeading, endPoint: .bottomTrailing) : LinearGradient(colors: [.secondary.opacity(0.3)], startPoint: .top, endPoint: .bottom))
                            .shadow(color: isActive ? activeGradient.first!.opacity(0.9) : .clear, radius: 4, y: 1)
                            .scaleEffect(isActive ? 1.25 : 1.0)
                            .zIndex(isActive ? 1 : 0)
                            .animation(.spring(response: 0.35, dampingFraction: 0.65), value: frequencyLog)
                            .position(x: geo.size.width * CGFloat(percent), y: geo.size.height / 2)
                    }
                }
                .frame(maxWidth: .infinity)
                .frame(height: isWide ? 36 : 32)
                
                Slider(value: $frequencyLog, in: 1...24, step: 0.1)
                    .tint(currentRegion.baseColor)
                    .background(
                        GeometryReader { geo in
                            RoundedRectangle(cornerRadius: 4)
                                .fill(spectrumGradient)
                                .frame(height: 6)
                                .position(x: geo.size.width / 2, y: geo.size.height / 2)
                        }
                    )
                
                HStack {
                    Text("10¹ Hz (ELF)")
                    Spacer()
                    Text("10¹⁴ Hz (Visible)")
                    Spacer()
                    Text("10²⁴ Hz (Gamma)")
                }
                .font(isWide ? .body.weight(.medium) : .caption.weight(.medium))
                .foregroundStyle(.secondary)
            }
            .padding(.top, 4)
        }
    }
    
    private func overviewBox(stretch: Bool, isWide: Bool) -> some View {
        PremiumCard(title: "Physical Overview", icon: "book.fill", baseColor: currentRegion.baseColor, gradientColors: currentRegion.gradientColors, stretchVertically: stretch, isWide: isWide) {
            Text(currentRegion.description)
                .font(isWide ? .title3 : .body)
                .lineSpacing(isWide ? 6 : 4)
                .padding(.top, 4)
                .fixedSize(horizontal: false, vertical: true)
        }
    }
    
    private func applicationsBox(stretch: Bool, isWide: Bool) -> some View {
        PremiumCard(title: "Real-World Applications", icon: "globe", baseColor: currentRegion.baseColor, gradientColors: currentRegion.gradientColors, stretchVertically: stretch, isWide: isWide) {
            VStack(alignment: .leading, spacing: isWide ? 14 : 10) {
                ForEach(currentRegion.applications, id: \.self) { app in
                    HStack(spacing: 12) {
                        Image(systemName: "checkmark.circle.fill")
                            .foregroundStyle(LinearGradient(colors: currentRegion.gradientColors, startPoint: .topLeading, endPoint: .bottomTrailing))
                            .font(isWide ? .title3 : .body)
                        Text(app)
                            .font((isWide ? Font.title3 : Font.body).weight(.medium))
                            .lineLimit(1)
                            .minimumScaleFactor(0.8)
                    }
                }
            }
            .padding(.top, 4)
        }
    }
}

    // MARK: - Premium Card Container
struct PremiumCard<Content: View>: View {
    var title: String? = nil
    var icon: String? = nil
    var baseColor: Color
    var gradientColors: [Color]
    var stretchVertically: Bool = false
    var isWide: Bool = false
    @ViewBuilder var content: () -> Content
    
    var body: some View {
        VStack(alignment: .leading, spacing: isWide ? 16 : 12) {
            if let title = title, let icon = icon {
                HStack(spacing: 8) {
                    Image(systemName: icon)
                        .font((isWide ? Font.title2 : Font.title3).weight(.semibold))
                        .foregroundStyle(LinearGradient(colors: gradientColors, startPoint: .topLeading, endPoint: .bottomTrailing))
                    Text(title)
                        .font((isWide ? Font.title2 : Font.title3).weight(.semibold))
                        .foregroundStyle(.primary)
                }
                Divider().opacity(0.5)
            }
            
            content()
                .frame(maxWidth: .infinity, alignment: .topLeading)
            
            // Forces the VStack to expand to the max height provided by the parent GridRow
            if stretchVertically {
                Spacer(minLength: 0)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: stretchVertically ? .infinity : nil, alignment: .topLeading)
        .padding(isWide ? 24 : 18)
        .background(
            ZStack {
                Rectangle().fill(.regularMaterial)
                LinearGradient(colors: gradientColors, startPoint: .topLeading, endPoint: .bottomTrailing).opacity(0.04)
            }
        )
        .clipShape(RoundedRectangle(cornerRadius: 16, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 16, style: .continuous)
                .stroke(baseColor.opacity(0.2), lineWidth: 1)
        )
        .shadow(color: baseColor.opacity(0.05), radius: 8, x: 0, y: 4)
    }
}

// MARK: - Dual Field Wave Visualizer (Electric & Magnetic)
struct DualFieldWaveVisualizer: View {
    var frequencyLog: Double
    var gradientColors: [Color]
    
    var body: some View {
        GeometryReader { geometry in
            ZStack {
                // Center propagation axis line
                Path { path in
                    path.move(to: CGPoint(x: 0, y: geometry.size.height / 2))
                    path.addLine(to: CGPoint(x: geometry.size.width, y: geometry.size.height / 2))
                }
                .stroke(Color.secondary.opacity(0.3), style: StrokeStyle(lineWidth: 1, dash: [4, 4]))
                
                // Magnetic Field Wave Path (B - Blue Offset)
                FieldWavePath(frequencyLog: frequencyLog, geometry: geometry, isMagnetic: true)
                    .stroke(LinearGradient(colors: [.blue, .cyan], startPoint: .leading, endPoint: .trailing), style: StrokeStyle(lineWidth: 2, lineCap: .round))
                
                // Electric Field Wave Path (E - Primary Region Gradient)
                FieldWavePath(frequencyLog: frequencyLog, geometry: geometry, isMagnetic: false)
                    .stroke(LinearGradient(colors: gradientColors, startPoint: .leading, endPoint: .trailing), style: StrokeStyle(lineWidth: 3, lineCap: .round))
                    .shadow(color: gradientColors.first!.opacity(0.5), radius: 4)
            }
        }
    }
}

private struct FieldWavePath: Shape {
    var frequencyLog: Double
    var geometry: GeometryProxy
    var isMagnetic: Bool
    
    var animatableData: Double {
        get { frequencyLog }
        set { frequencyLog = newValue }
    }
    
    func path(in rect: CGRect) -> Path {
        var path = Path()
        let width = geometry.size.width
        let height = geometry.size.height
        let midY = height / 2.0
        
        let mappedFrequency = max(1.5, frequencyLog - 2.0)
        let visualWavelength = width / CGFloat(mappedFrequency)
        
        let baseAmplitude = (height / 2.5) * (1.0 - (frequencyLog / 45.0))
        
        path.move(to: CGPoint(x: 0, y: midY))
        
        for x in stride(from: 0, through: width, by: 1) {
            let relativeX = x / visualWavelength
            let sineValue = sin(relativeX * .pi * 2)
            
            if isMagnetic {
                let y = midY + (sineValue * baseAmplitude * 0.45)
                path.addLine(to: CGPoint(x: x, y: y))
            } else {
                let y = midY + (sineValue * baseAmplitude)
                path.addLine(to: CGPoint(x: x, y: y))
            }
        }
        
        return path
    }
}

#Preview {
    NavigationStack {
        ElectromagneticWaveAnalyzerView()
    }
}
